%% Default Author details used by scripts
%% Several fields below can accommodate URL links
\makeatletter
\newcommand{\Salutation}{Dr.}
\newcommand{\FirstName}{Lieuwe}
\newcommand{\LastName}{Leene}
\newcommand{\Certification}{PhD MSc}
\newcommand{\Email}{lieuwe.leene@novelda.com}
\newcommand{\JobTitle}{Senior IC Design Engineer}
\newcommand{\Group}{Xethru Engineering Division}
\newcommand{\Organisation}{Novelda}
\newcommand{\Address}{12F Helgesens Gate, Oslo, 0553 Norway}
\newcommand{\Telephone}{+44 (0)7544 757250}
\newcommand{\LinkedIn}{lieuwe-leene}
\newcommand{\Website}{www.xethru.com}
\makeatother
