%% Default Author details used by scripts
%% Several fields below can accommodate URL links
\makeatletter
\newcommand{\Salutation}{Mr.}
\newcommand{\FirstName}{John}
\newcommand{\LastName}{Dough}
\newcommand{\Certification}{MCA}
\newcommand{\Email}{j.dough@baker.br}
\newcommand{\JobTitle}{Technical Oven Assistant}
\newcommand{\Group}{Main Baking staff for Bread}
\newcommand{\Organisation}{A Baking Company for Bread, Anytown, USA}
\newcommand{\Address}{123 Main St, Anytown, 90210 USA}
\newcommand{\Telephone}{+88 (0)8888 888888}
\newcommand{\LinkedIn}{john-dough}
\newcommand{\Website}{www.baker.br/oven-corner}
\newcommand{\Creditation}{MCA}
\makeatother
