%% Default Author details used by scripts
%% Several fields below can accommodate URL links
\makeatletter
\newcommand{\Salutation}{Dr.}
\newcommand{\FirstName}{Lieuwe}
\newcommand{\LastName}{Leene}
\newcommand{\Certification}{PhD. MSc. BEng.}
\newcommand{\Email}{lieuwe.leene@novelda.com}
\newcommand{\JobTitle}{Mixed Signal IC Design Lead}
\newcommand{\Group}{Novelda Engineering Division}
\newcommand{\Organisation}{Novelda}
\newcommand{\Address}{12F Helgesens Gate, Oslo, 0553 Norway}
\newcommand{\Telephone}{(+47) 74 686 755}
\newcommand{\LinkedIn}{lieuwe-leene}
\newcommand{\Website}{lieuwe.leene.dev}
\makeatother
